#!/bin/bash
set -e

# Remove files
rm -f /usr/local/bin/mint-cleaner
rm -f /usr/share/applications/mint-cleaner.desktop
rm -f /usr/share/icons/hicolor/scalable/apps/system-cleaner.svg

# Update caches
gtk-update-icon-cache /usr/share/icons/hicolor || true
update-desktop-database /usr/share/applications || true
